apiVersion: v1 # String scalar
kind: Pod # String scalar
metadata: # Dictionary
  name: my-pod-2 # String scalar
  labels: # Nested Dictionary
    app: nginx # String scalar
    environment: development # String scalar
spec: # Dictionary
  containers: # List
    - name: nginx-container # String scalar
      image: nginx # String scalar
      ports: # **Nested List**
        - containerPort: 80 # Integer scalar
    - name: sidecar-container # String scalar
      image: busybox # String scalar
      args: # ["sleep", "3600"] # Nested List
        - "sleep"
        - "3600"