apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 11  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:  # Node selector to specify nodes for deployment
        department: ecommerce  # all pods will be scheduled to those nodes with label department=ecommerce
      containers:
      - name: nginx-app
        image: nginx:latest  # NGINX Docker image
        ports:
        - containerPort: 80  # Port NGINX listens on

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment2
#   labels:
#     app: nginx
# spec:
#   replicas: 5  # Number of NGINX pods to run
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       nodeName: multinode-demo-m04
#       containers:
#       - name: nginx-app
#         image: nginx:latest  # NGINX Docker image
#         ports:
#         - containerPort: 80  # Port NGINX listens on