apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 11  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: department
                operator: In
                values:
                - "ecommerce"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx-app
        image: nginx:latest  # NGINX Docker image
        ports:
        - containerPort: 80  # Port NGINX listens on