apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - nginx
          - apache
  template:
    metadata:
      labels:
        app: apache
        environment: development
    spec:
      containers:
        - name: nginx-container
          image: nginx