apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchLabels:
      Location: India   # Match the labels in the template
  template:
    metadata:
      name: testpod7
      labels:
        Location: India   # Match the selector
    spec:
      containers:
      - name: container1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo ReplicaSet Example; sleep 5 ; done"]