apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica-2
spec:
  replicas: 2
  selector:
    Location: US
  template:
    metadata:
      name: testpod6
      labels:
        Location: US
    spec:
      containers:
      - name: c00
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo ReplicationController Example; sleep 5 ; done"]