apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
spec:
  acme:                           
    server: https://acme-v02.api.letsencrypt.org/directory
    email: princewillopah.dev@gmail.com                                   # replace with your real email
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx