apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.mongo.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.mongo.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.mongo.rootUsernameKey }}
      remoteRef:
        key: {{ .Values.aws.mongoSecretRemotePath }}
        property: {{ .Values.aws.mongoRootUsernameKey }}
    - secretKey: {{ .Values.mongo.rootPasswordKey }}
      remoteRef:
        key: {{ .Values.aws.mongoSecretRemotePath }}
        property: {{ .Values.aws.mongoRootPasswordKey }}
