apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.aws.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.aws.credentials.secretName }}
            key: {{ .Values.aws.credentials.accessKeyField }}
          secretAccessKeySecretRef:
            name: {{ .Values.aws.credentials.secretName }}
            key: {{ .Values.aws.credentials.secretKeyField }}
