apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: shopsphere
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: my-access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: my-secret-access-key
