apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-retain
provisioner:  k8s.io/minikube-hostpath    # for aws ebs use ebs.csi.aws.com
volumeBindingMode: Immediate #it defines how exacly a pv will be created / if "immediate" is specified, the pv is created immediately when the pvc is created /  when we spcify "WaitForFirstConsumer" the pv is not created until the pvc is used by a pod
reclaimPolicy: Delete  # it defines what happens if pvc is deleted - "Delete" means deleted pv when pvc is deleted / "Retain" means do not delete pv when pvc is deleted