apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: shopsphere
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: shopsphere/prod/backend
