apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: shopsphere
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt-token           # The key name inside the K8s Secret to be used by the backend (just choose any random meaningful name here)
    remoteRef:
      key: shopsphere/prod/backend       # The name of the secret in AWS secret manager
      property: jwt-secret               # The specific JSON key in AWS
  - secretKey: backend-mongo-uri
    remoteRef:
      key: shopsphere/prod/backend
      property: mongo-uri