apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80