apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
- ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -dev

namePrefix: app1-

labels:
- includeSelectors: true
  pairs:
    env: dev

images:
- name: nginx
  newName: nginx
  newTag: latest

commonAnnotations:
  branch: dev
  support: 800-800

namespace: dev

replicas:
- count: 2
  name: nginx-deploy

patches:
- path: patch-container.yaml
