apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: frontend-secret
      containers:
        - name: frontend-container
          image: nginx
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: DB_PASSWORD
          volumeMounts:
          - name: secret-volume
            mountPath: /etc/secrets
            readOnly: true