apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -dev

namePrefix: app1-

labels:
  - pairs:
      env: dev
    includeSelectors: true

images:
- name: nginx # Will look for container with image name nginx
  newName: nginx
  newTag: "latest"

commonAnnotations:
  branch: dev
  support: 800-800

namespace: dev

replicas:
- name: nginx-deploy
  count: 2