apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: testing
    department: DevOps
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo This is Day07 of 30DaysOfKubernetes; sleep 5; done"]
  - name: container2
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    env: testing
    department: DevOps
spec:
  containers:
  - name: container3
    image: nginx