apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: testing
    department: DevOps
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo This is Day07 of 30DaysOfKubernetes; sleep 5; done"]
  - name: container2
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    env: testing
    department: DevOps 
    app: nginx #Add the label to container3 so that the Service selector can match

spec:
  containers:
  - name: container3
    image: nginx

---
# Loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: container1-and-2-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # Change the service type to ClusterIP (default) as we are not using external load balancing
  type: ClusterIP

  