apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: workload-editor
rules:
# Rule 1: Allow Seema to create and list Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list"]
# Rule 2: Allow Seema to create and list Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-workload-editor
  namespace: dev
subjects:
# Subject 1: Individual user Seema
- kind: User
  name: seema
  apiGroup: rbac.authorization.k8s.io
# Subject 2: Group of junior admins
- kind: Group
  name: junior-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: workload-editor
  apiGroup: rbac.authorization.k8s.io