apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  # Rule: Allow read-only access to Node resources
  - apiGroups: [""]
    resources: ["nodes"]        
    verbs: ["get", "list", "watch"] 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-node-reader    
subjects:
  # Subject: Grant access to user 'seema'
  - kind: User
    name: seema
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole                   
  name: node-reader                     
  apiGroup: rbac.authorization.k8s.io