apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elevated-workload-editor              
rules:
  # Rule 1: Manage Pods in the core API group
  - apiGroups: [""]                            
    resources: ["pods"]                        
    verbs: ["create", "delete", "update"]    

  # Rule 2: Manage Deployments in the 'apps' API group
  - apiGroups: ["apps"]                       
    resources: ["deployments"]                 
    verbs: ["create", "delete", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-clusterrole-in-prod
  namespace: prod                              # This binding is namespace-scoped
roleRef:
  kind: ClusterRole                            # Refers to a ClusterRole
  name: elevated-workload-editor
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Bind to user Seema
  - kind: User
    name: seema
    apiGroup: rbac.authorization.k8s.io
