apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-static-site
spec:
  containers:
  - name: nginx
    image: princewillopah/nginx-static-gym-website:v1
    ports:
    - containerPort: 80



