apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: shopsphere
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
  - secretKey: mongodb-usr           # The key name inside the K8s Secret(just choose any random meaningful name here)
    remoteRef:
      key: shopsphere/prod/mongo       # The name of the secret in AWS
      property: mongo-root-username # The specific JSON key in AWS
  - secretKey: mongodb-pwd
    remoteRef:
      key: shopsphere/prod/mongo
      property: mongo-root-password
  - secretKey: mongo-expr-urs           # The key name inside the K8s Secret(just choose any random meaningful name here)
    remoteRef:
      key: shopsphere/prod/mongo       # The name of the secret in AWS
      property: mongo-express-username # The specific JSON key in AWS
  - secretKey: mongo-expr-pwd
    remoteRef:
      key: shopsphere/prod/mongo
      property: mongo-express-password