# 11. DB SEED JOB (with dependencies)
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
  namespace: shopsphere
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo; sleep 5; done;']
      containers:
        - name: seed
          image: princewillopah2/shopsphere-backend:1.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Testing MongoDB connection..."
              sleep 5
              echo "Starting seed script..."
              npm run seed
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: backend-mongo-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-token
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: node-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"