apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
  labels:
    name: myapp
spec:
  volumes:
    - name: temp-storage
      emptyDir: {}
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
      - mountPath: /data
        name: temp-storage
  - name: busybox-2
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
      - mountPath: /data
        name: temp-storage