apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-demo
spec:
  containers:
  - name: busybox-app
    image: busybox
    command: ["sh", "-c", "touch /tmp/ready; sleep 3600"] # Create /tmp/ready file and keep container alive for 1 hour
    readinessProbe:
      exec:                       # Executes a command inside the container
        command:
        - cat
        - /tmp/ready               # Checks if /tmp/ready file exists; probe succeeds if file exists
      initialDelaySeconds: 5       # Waits 5 seconds before starting the first probe
      periodSeconds: 5          
      failureThreshold: 1          