apiVersion: v1
kind: Pod
metadata:
  name: demo-multi-container-pod
  labels:
    app: demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers:
  - name: init-file-writer
    image: busybox
    command: ['sh', '-c', 'echo "<h1>Hello from Init Container</h1>" > /data/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /data

  containers:
  - name: nginx-server
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: sidecar-logger
    image: busybox
    command: ['sh', '-c', 'while true; do echo "$(date) sidecar log entry" >> /data/logs.txt; sleep 5; done']
    volumeMounts:
    - name: shared-data
      mountPath: /data













