apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 512Mi
    min:
      cpu: 100m
      memory: 50Mi
    default:
      cpu: 200m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 50Mi
    maxLimitRequestRatio:
      cpu: "2"
      memory: "4"
  - type: Pod
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 50Mi
    maxLimitRequestRatio:
      cpu: "2"
      memory: "4"
