apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    configmaps: "10"
    persistentvolumeclaims: "5"
    replicationcontrollers: "10"
    secrets: "10"
    services: "5"
    services.loadbalancers: "2"
    services.nodeports: "2"
    resourcequotas: "1"
    pods.metrics.k8s.io: "50"
    replicationcontrollers.metrics.k8s.io: "20"
    services.metrics.k8s.io: "20"
