apiVersion: apps/v1
kind: Deployment
metadata:
  name: na-deploy
spec:
  replicas: 20
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storage
                operator: In
                values:
                  - ssd
              - key: env
                operator: In
                values:
                  - prod
      containers:
        - name: nginx
          image: nginx