apiVersion: v1
kind: Namespace
metadata:
  name: sc
  labels:
    name: secrets-configmaps
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-plain
  namespace: sc
type: Opaque
stringData:
  # WARNING: This is NOT secure - secrets are in plain text
  username: admin
  password: secretpassword123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: sc
data:
  database-name: "myappdb"
  max-connections: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-plain
  namespace: sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-plain
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-plain
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database-name
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mongodb/config
      volumes:
      - name: config-volume
        configMap:
          name: mongodb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: sc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017