apiVersion: v1
kind: Namespace
metadata:
  name: sc
  labels:
    name: secrets-configmaps
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-encoded
  namespace: sc
type: Opaque
data:
  # Base64 encoded values
  # echo -n "admin" | base64 -> YWRtaW4=
  # echo -n "SecretPass2024!" | base64 -> U2VjcmV0UGFzczIwMjQh
  username: YWRtaW4=
  password: U2VjcmV0UGFzczIwMjQh
  replica-set-key: c3VwZXJTZWN1cmVSZXBsaWNhS2V5MTIz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: sc
data:
  database-name: "myappdb"
  max-connections: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-encoded
  namespace: sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-encoded
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-encoded
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database-name
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mongodb/config
      volumes:
      - name: config-volume
        configMap:
          name: mongodb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: sc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017