apiVersion: v1
kind: Pod
metadata:
  name: mongo-test-client
  namespace: sc
spec:
  containers:
  - name: mongo-client
    image: mongo:6
    command: ["sleep", "3600"]
    env:
    - name: MONGO_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-kubectl-secret
          key: username
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-kubectl-secret
          key: password