apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-external-db-secret
  namespace: shopsohere
spec:
  refreshInterval: 1h             # How often ESO checks AWS for updates
  secretStoreRef:
    name: aws-secretsmanager      # Must match your SecretStore name
    kind: SecretStore
  target:
    name: mongo-k8s-secret        # The name of the Secret ESO will CREATE in K8s
    creationPolicy: Owner         # ESO will manage the lifecycle of this secret
  data:
  - secretKey: username           # The key name inside the K8s Secret(just choose any random meaningful name here)
    remoteRef:
      key: shopsohere/mongo       # The name of the secret in AWS
      property: MONGO_ROOT_USERNAME # The specific JSON key in AWS
  - secretKey: password
    remoteRef:
      key: shopsohere/mongo
      property: MONGO_ROOT_PASSWORD